import AppKit

/// Polls the system pasteboard for changes. macOS has no "clipboard changed"
/// notification, so watching `changeCount` on a short timer is the standard approach —
/// and it needs no special permissions.
@MainActor
final class ClipboardWatcher {
    /// Pasteboard types that mean "do not record this" — password managers and
    /// similar tools mark their payloads with these.
    private static let secretTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("com.typeit4me.clipping"),
        NSPasteboard.PasteboardType("Pasteboard generator type")
    ]

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Set while we write to the pasteboard ourselves, so we don't record our own paste.
    var suppressNextChange = false

    var isPaused = false

    var onCapture: ((ClipItem) -> Void)?

    init() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        stop()
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        if suppressNextChange {
            suppressNextChange = false
            return
        }
        guard !isPaused else { return }

        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: Self.secretTypes) else { return }

        guard let item = capture() else { return }
        onCapture?(item)
    }

    /// Turns whatever is on the pasteboard right now into a `ClipItem`.
    private func capture() -> ClipItem? {
        let app = NSWorkspace.shared.frontmostApplication
        let appName = app?.localizedName
        let bundleID = app?.bundleIdentifier

        // Ignore anything we put there ourselves.
        guard bundleID != Bundle.main.bundleIdentifier else { return nil }

        // 1. Files dragged or copied from Finder.
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path).joined(separator: "\n")
            return ClipItem(
                kind: .file,
                text: paths,
                sourceAppName: appName,
                sourceBundleID: bundleID
            )
        }

        // 2. Images (screenshots, copied graphics).
        if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff),
           let filename = saveImage(data: data) {
            return ClipItem(
                kind: .image,
                text: "Image copied from \(appName ?? "another app")",
                imageFile: filename,
                sourceAppName: appName,
                sourceBundleID: bundleID
            )
        }

        // 3. Plain text — the common case.
        if let string = pasteboard.string(forType: .string) {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return nil }

            let isURL = trimmed.split(separator: " ").count == 1
                && (trimmed.hasPrefix("http://") || trimmed.hasPrefix("https://"))

            return ClipItem(
                kind: isURL ? .url : .text,
                text: string,
                sourceAppName: appName,
                sourceBundleID: bundleID
            )
        }

        return nil
    }

    /// Normalises pasteboard image data to PNG on disk, returning the filename.
    private func saveImage(data: Data) -> String? {
        guard let rep = NSBitmapImageRep(data: data),
              let png = rep.representation(using: .png, properties: [:])
        else { return nil }

        let filename = "\(UUID().uuidString).png"
        let url = ClipboardStore.imagesFolder.appendingPathComponent(filename)
        do {
            try png.write(to: url, options: .atomic)
            return filename
        } catch {
            NSLog("Stash: could not save image — \(error.localizedDescription)")
            return nil
        }
    }
}
